// Code generated by codegen DO NOT EDIT.
// source: /tmp/user_create_test.yaml
// version: 0.1.0

package handler

import (
	"context"
	"errors"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/example/app/testdata/output/user_create/domain"
)

// UserCreateServiceIface is the contract handler requires from the service layer.
// The service must implement this interface — checked at compile time in main.
type UserCreateServiceIface interface {
	Create(ctx context.Context, req *domain.UserCreateRequest) (*domain.UserCreateResponse, error)
}

// UserCreateHandler handles HTTP requests for the UserCreate vertical slice.
type UserCreateHandler struct {
	svc UserCreateServiceIface
}

// NewUserCreateHandler creates a new UserCreateHandler.
func NewUserCreateHandler(svc UserCreateServiceIface) *UserCreateHandler {
	return &UserCreateHandler{svc: svc}
}

// Register mounts the handler routes onto the provided RouterGroup.
func (h *UserCreateHandler) Register(r *gin.RouterGroup) {
	r.POST("/api/v1/users", h.handle)
}

func (h *UserCreateHandler) handle(c *gin.Context) {
	var req domain.User_createRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	resp, err := h.svc.Create(c.Request.Context(), &req)
	if err != nil {
		h.handleError(c, err)
		return
	}
	c.JSON(http.StatusOK, resp)
}

func (h *UserCreateHandler) handleError(c *gin.Context, err error) {
	switch {
	case errors.Is(err, domain.ErrUserCreateNotFound):
		c.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
	case errors.Is(err, domain.ErrUserCreateValidation):
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
	case errors.Is(err, domain.ErrUserCreateDomain):
		c.JSON(http.StatusConflict, gin.H{"error": err.Error()})
	default:
		c.JSON(http.StatusInternalServerError, gin.H{"error": "internal server error"})
	}
}
