// Code generated by codegen DO NOT EDIT.
// source: testdata/schemas/user_create.yaml
// version: 0.1.0

package service

import (
	"context"

	"github.com/example/app/testdata/output/user/domain"
)

// UserRepositoryIface is the contract service requires from the repository layer.
// The repository must implement this interface — checked at compile time in main.
type UserRepositoryIface interface {
	Create(ctx context.Context, req *domain.UserRequest) (*domain.UserResponse, error)
}

// UserService contains the business logic for User.
type UserService struct {
	repo UserRepositoryIface
}

// NewUserService creates a new UserService.
func NewUserService(repo UserRepositoryIface) *UserService {
	return &UserService{repo: repo}
}
