// Code generated by codegen DO NOT EDIT.
// source: /tmp/user_create_test.yaml
// version: 0.1.0

package service

import (
	"context"

	"github.com/example/app/testdata/output/user_create/domain"
)

// UserCreateRepositoryIface is the contract service requires from the repository layer.
// The repository must implement this interface — checked at compile time in main.
type UserCreateRepositoryIface interface {
	Create(ctx context.Context, req *domain.UserCreateRequest) (*domain.UserCreateResponse, error)
}

// UserCreateService contains the business logic for UserCreate.
type UserCreateService struct {
	repo UserCreateRepositoryIface
}

// NewUserCreateService creates a new UserCreateService.
func NewUserCreateService(repo UserCreateRepositoryIface) *UserCreateService {
	return &UserCreateService{repo: repo}
}
