// Code generated by codegen DO NOT EDIT.
// source: testdata/schemas/user_create.yaml
// version: 0.1.0

package service

import (
	"context"

	"github.com/example/app/internal/user/domain"
)

// UserService implements domain.UserServiceIface.
type UserService struct {
	repo domain.UserRepository
}

// NewUserService creates a new UserService with the given repository.
func NewUserService(repo domain.UserRepository) *UserService {
	return &UserService{repo: repo}
}

// Create implements the User business logic.
func (s *UserService) Create(ctx context.Context, req *domain.UserRequest) (*domain.UserResponse, error) {
	// TODO: implement Create
	// Generated by codegen (noop provider). Replace with your logic.
	panic("not implemented: Create")
}
