// Code generated by codegen DO NOT EDIT.
// source: /tmp/user_create_test.yaml
// version: 0.1.0

package domain

import (
	"errors"
)

// UserCreateRequest is the input for the Create operation.
type UserCreateRequest struct {
	Name string `json:"name" binding:"required"`
}

// UserCreateResponse is the output for the Create operation.
type UserCreateResponse struct {
	Id string `json:"id"`
}

// Domain errors returned by the UserCreate vertical slice.
var (
	ErrUserCreateDomain     = errors.New("user_create domain error")
	ErrUserCreateValidation = errors.New("user_create validation error")
	ErrUserCreateInternal   = errors.New("user_create internal error")
	ErrUserCreateNotFound   = errors.New("user_create not found")
)
