// Code generated by codegen DO NOT EDIT.
// source: testdata/schemas/user_create.yaml
// version: 0.1.0

package handler

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"errors"

	"github.com/example/app/internal/user/domain"
)

// UserHandler handles HTTP requests for the User vertical slice.
type UserHandler struct {
	svc domain.UserServiceIface
}

// NewUserHandler creates a new UserHandler.
func NewUserHandler(svc domain.UserServiceIface) *UserHandler {
	return &UserHandler{svc: svc}
}

// Register mounts the handler routes onto the provided RouterGroup.
func (h *UserHandler) Register(r *gin.RouterGroup) {
	r.POST("/api/v1/users", h.handle)
}

func (h *UserHandler) handle(c *gin.Context) {
	var req domain.UserRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	resp, err := h.svc.Create(c.Request.Context(), &req)
	if err != nil {
		h.handleError(c, err)
		return
	}
	c.JSON(http.StatusOK, resp)
}

func (h *UserHandler) handleError(c *gin.Context, err error) {
	switch {
	case errors.Is(err, domain.ErrUserNotFound):
		c.JSON(http.StatusNotFound, gin.H{"error": err.Error()})
	case errors.Is(err, domain.ErrUserValidation):
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
	case errors.Is(err, domain.ErrUserDomain):
		c.JSON(http.StatusConflict, gin.H{"error": err.Error()})
	default:
		c.JSON(http.StatusInternalServerError, gin.H{"error": "internal server error"})
	}
}
