package ai

import (
	"context"
	"fmt"
)

// NoopProvider генерирует заглушку с паникой TODO для каждого метода.
// Является провайдером по умолчанию и не требует внешних зависимостей.
type NoopProvider struct{}

func (NoopProvider) Name() string { return "noop" }

func (NoopProvider) GenerateMethodBody(_ context.Context, req MethodRequest) (string, error) {
	return fmt.Sprintf(
		"\t// TODO: implement %s\n\t// Generated by codegen (noop provider). Replace with your logic.\n\tpanic(\"not implemented: %s\")",
		req.MethodName,
		req.MethodName,
	), nil
}
