package ai

import (
	"context"
	"fmt"
)

// NoopProvider emits a TODO panic stub for every method.
// It is the default provider and requires no external dependencies.
type NoopProvider struct{}

func (NoopProvider) Name() string { return "noop" }

func (NoopProvider) GenerateMethodBody(_ context.Context, req MethodRequest) (string, error) {
	return fmt.Sprintf(
		"\t// TODO: implement %s\n\t// Generated by codegen (noop provider). Replace with your logic.\n\tpanic(\"not implemented: %s\")",
		req.MethodName,
		req.MethodName,
	), nil
}
