package repository

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"bytes"

	"github.com/Enthreeka/magister-work/internal/generator"
	"github.com/Enthreeka/magister-work/internal/schema"
)

// SqlcStrategy generates the repository layer via the sqlc toolchain.
// It supports two modes:
//   - generate: codegen writes sqlc.yaml + .sql files, then calls `sqlc generate`.
//   - existing: codegen reads the user's sqlc.yaml to derive the RepositoryContract
//     and generates only service + handler layers on top of it.
type SqlcStrategy struct{}

func (SqlcStrategy) Name() string { return "sqlc" }

func (s SqlcStrategy) Prepare(ctx context.Context, sc *schema.Schema, opts Options) error {
	if sc.Repository.Sqlc == nil || sc.Repository.Sqlc.Mode != "generate" {
		return nil
	}
	return s.runSqlcGenerate(ctx, sc, opts)
}

func (SqlcStrategy) Contract(s *schema.Schema) (*RepositoryContract, error) {
	d := strings.Title(strings.ToLower(s.Domain))
	return &RepositoryContract{
		InterfaceName: d + "Repository",
		MethodName:    operationToMethod(s.Repository.Operation),
		InputType:     d + "Request",
		OutputType:    d + "Response",
	}, nil
}

func (s SqlcStrategy) Files(sc *schema.Schema, opts Options) ([]generator.File, error) {
	if sc.Repository.Sqlc == nil {
		return nil, fmt.Errorf("sqlc strategy: missing sqlc configuration")
	}

	switch sc.Repository.Sqlc.Mode {
	case "generate":
		return s.generateFiles(sc, opts)
	case "existing":
		// In existing mode codegen does not write any repository files.
		// Service and handler layers are generated on top of the user's sqlc types.
		return nil, nil
	default:
		return nil, fmt.Errorf("sqlc strategy: unknown mode %q", sc.Repository.Sqlc.Mode)
	}
}

// generateFiles produces the sqlc config and SQL query file that will be
// consumed by `sqlc generate` (called in Prepare).
func (SqlcStrategy) generateFiles(s *schema.Schema, opts Options) ([]generator.File, error) {
	domain := strings.ToLower(s.Domain)
	baseDir := strings.TrimRight(opts.OutputDir, "/")

	sqlcYAML, err := buildSqlcYAML(s, domain, baseDir)
	if err != nil {
		return nil, err
	}
	sqlQuery, err := buildSQLQuery(s)
	if err != nil {
		return nil, err
	}

	return []generator.File{
		{
			Path:      filepath.Join(baseDir, domain, "gen", "sqlc", "sqlc.gen.yaml"),
			Content:   []byte(sqlcYAML),
			Protected: true,
		},
		{
			Path:      filepath.Join(baseDir, domain, "gen", "sqlc", "queries.gen.sql"),
			Content:   []byte(sqlQuery),
			Protected: true,
		},
	}, nil
}

const sqlcYAMLTmpl = `# Code generated by codegen DO NOT EDIT.
version: "2"
sql:
  - engine: "postgresql"
    queries: "./queries.gen.sql"
    schema: "."
    gen:
      go:
        package: "db"
        out: "../../db"
        emit_json_tags: true
        emit_prepared_queries: false
`

func buildSqlcYAML(_ *schema.Schema, _, _ string) (string, error) {
	return sqlcYAMLTmpl, nil
}

const sqlQueryTmpl = `-- Code generated by codegen DO NOT EDIT.
-- source: {{.SourceFile}}
{{ $op := .Operation -}}
{{ if eq $op "insert" -}}
-- name: {{.MethodName}} :one
INSERT INTO {{.Schema}}.{{.Table}} ({{.Columns}})
VALUES ({{.Placeholders}})
RETURNING {{.ReturningCols}};
{{ else if eq $op "select" -}}
-- name: {{.MethodName}} :one
SELECT {{.SelectCols}}
FROM {{.Schema}}.{{.Table}}
WHERE {{.WhereClause}};
{{ else if eq $op "update" -}}
-- name: {{.MethodName}} :exec
UPDATE {{.Schema}}.{{.Table}}
SET {{.SetClause}}
WHERE {{.WhereClause}};
{{ else if eq $op "delete" -}}
-- name: {{.MethodName}} :exec
DELETE FROM {{.Schema}}.{{.Table}}
WHERE {{.WhereClause}};
{{ end }}`

type sqlQueryData struct {
	SourceFile    string
	MethodName    string
	Operation     string
	Schema        string
	Table         string
	Columns       string
	Placeholders  string
	ReturningCols string
	SelectCols    string
	WhereClause   string
	SetClause     string
}

func buildSQLQuery(s *schema.Schema) (string, error) {
	cols := s.Repository.Fields
	ph := make([]string, len(cols))
	for i := range cols {
		ph[i] = fmt.Sprintf("$%d", i+1)
	}
	outCols := make([]string, len(s.Output))
	for i, f := range s.Output {
		outCols[i] = f.Name
	}
	whereParts := make([]string, len(cols))
	for i, c := range cols {
		whereParts[i] = fmt.Sprintf("%s = $%d", c, i+1)
	}
	setParts := make([]string, len(cols))
	for i, c := range cols {
		setParts[i] = fmt.Sprintf("%s = $%d", c, i+1)
	}

	data := sqlQueryData{
		SourceFile:    "system-gen.yaml",
		MethodName:    operationToMethod(s.Repository.Operation),
		Operation:     strings.ToLower(s.Repository.Operation),
		Schema:        s.Repository.Schema,
		Table:         s.Repository.Table,
		Columns:       strings.Join(cols, ", "),
		Placeholders:  strings.Join(ph, ", "),
		ReturningCols: strings.Join(outCols, ", "),
		SelectCols:    strings.Join(outCols, ", "),
		WhereClause:   strings.Join(whereParts, " AND "),
		SetClause:     strings.Join(setParts, ", "),
	}

	tmpl, err := template.New("sql").Parse(sqlQueryTmpl)
	if err != nil {
		return "", fmt.Errorf("sqlc strategy: parse sql template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("sqlc strategy: execute sql template: %w", err)
	}
	return buf.String(), nil
}

// runSqlcGenerate writes the generated files to disk and invokes `sqlc generate`.
func (s SqlcStrategy) runSqlcGenerate(ctx context.Context, sc *schema.Schema, opts Options) error {
	files, err := s.generateFiles(sc, opts)
	if err != nil {
		return err
	}

	// Write files before running sqlc
	for _, f := range files {
		if err := os.MkdirAll(filepath.Dir(f.Path), 0o755); err != nil {
			return fmt.Errorf("sqlc strategy: mkdir %s: %w", filepath.Dir(f.Path), err)
		}
		if err := os.WriteFile(f.Path, f.Content, 0o644); err != nil {
			return fmt.Errorf("sqlc strategy: write %s: %w", f.Path, err)
		}
	}

	// Determine the directory containing sqlc.gen.yaml
	domain := strings.ToLower(sc.Domain)
	baseDir := strings.TrimRight(opts.OutputDir, "/")
	sqlcDir := filepath.Join(baseDir, domain, "gen", "sqlc")

	cmd := exec.CommandContext(ctx, "sqlc", "generate")
	cmd.Dir = sqlcDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("sqlc strategy: sqlc generate failed: %w\n(is sqlc installed? run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest)", err)
	}
	return nil
}
