// Code generated by codegen DO NOT EDIT.
// source: testdata/schemas/user_create.yaml
// version: 0.1.0

package repository

import (
	"context"
	"fmt"
	"time"
	"github.com/example/app/testdata/output/user/domain"
	"github.com/jackc/pgx/v5/pgxpool"
)

type UserRepositoryImpl struct {
	db *pgxpool.Pool
}

func NewUserRepository(db *pgxpool.Pool) *UserRepositoryImpl {
	return &UserRepositoryImpl{db: db}
}

func (r *UserRepositoryImpl) Create(ctx context.Context, req *domain.UserRequest) (*domain.UserResponse, error) {
	query := `INSERT INTO public.users (name, email)
	VALUES ($1, $2)
	RETURNING id, created_at`

	row := r.db.QueryRow(ctx, query, req.Name, req.Email)

	var resp domain.UserResponse
	if err := row.Scan(&resp.Id, &resp.CreatedAt); err != nil {
		return nil, fmt.Errorf("repository.Create: %w", err)
	}
	return &resp, nil
}
