package generator

import (
	"os"
	"strings"
)

const generatedHeader = "// Code generated by codegen DO NOT EDIT."

// File представляет файл, который должен быть записан генератором.
type File struct {
	// Path — путь назначения относительно корня проекта.
	Path string
	// Content — тело файла, включая сгенерированный заголовок.
	Content []byte
	// Protected помечает файлы в зоне gen/, которыми codegen владеет исключительно.
	// Незащищённые файлы (заглушки) записываются только если они ещё не существуют.
	Protected bool
}

// IsGenerated возвращает true, если существующий файл на диске был создан codegen.
// Проверяет наличие заголовка DO NOT EDIT в первых 5 строках.
func IsGenerated(path string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	lines := strings.SplitN(string(data), "\n", 6)
	for i, line := range lines {
		if i >= 5 {
			break
		}
		if strings.Contains(line, generatedHeader) {
			return true, nil
		}
	}
	return false, nil
}

// Header формирует стандартный комментарий-заголовок сгенерированного файла.
func Header(sourceFile, version string) string {
	return generatedHeader + "\n" +
		"// source: " + sourceFile + "\n" +
		"// version: " + version + "\n\n"
}
