package generator

import (
	"os"
	"strings"
)

const generatedHeader = "// Code generated by codegen DO NOT EDIT."

// File represents a file to be written by the generator.
type File struct {
	// Path is the destination path relative to the project root.
	Path string
	// Content is the file body including the generated header.
	Content []byte
	// Protected marks files in the gen/ zone that codegen owns exclusively.
	// Non-protected files (stubs) are only written if they do not exist yet.
	Protected bool
}

// IsGenerated returns true if the existing file on disk was produced by codegen.
// It checks for the DO NOT EDIT header in the first 5 lines.
func IsGenerated(path string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	lines := strings.SplitN(string(data), "\n", 6)
	for i, line := range lines {
		if i >= 5 {
			break
		}
		if strings.Contains(line, generatedHeader) {
			return true, nil
		}
	}
	return false, nil
}

// Header builds the standard generated-file header comment.
func Header(sourceFile, version string) string {
	return generatedHeader + "\n" +
		"// source: " + sourceFile + "\n" +
		"// version: " + version + "\n\n"
}
